# Generated by Django 5.1.2 on 2026-05-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
